package org.howard.edu.lsp.finale.question1;

import java.util.HashMap;
import java.util.Map;

/**
 * Password generation service that provides a single access point for generating
 * passwords using various algorithms. This service uses the Singleton pattern to
 * ensure only one instance exists, and the Strategy pattern to allow runtime
 * selection and swapping of password generation algorithms.
 * 
 * @author Final Exam
 * @version 1.0
 */
public class PasswordGeneratorService {
    
    /*
     * ============================================================================
     * DESIGN PATTERN DOCUMENTATION
     * ============================================================================
     * 
     * PATTERNS USED:
     * 1. Singleton Pattern
     * 2. Strategy Pattern
     * 
     * WHY THESE PATTERNS WERE APPROPRIATE:
     * 
     * 1. SINGLETON PATTERN:
     *    - The requirement states "Only one instance of the service may exist"
     *    - Singleton ensures a single shared access point (getInstance())
     *    - Prevents multiple instances from being created
     *    - Provides global access to the service throughout the application
     *    - The private constructor prevents external instantiation
     *    - The static getInstance() method returns the single instance
     * 
     * 2. STRATEGY PATTERN:
     *    - The requirement states "Support multiple approaches to password generation"
     *    - The requirement states "Allow the caller to select the approach at run time"
     *    - The requirement states "Support future expansion of password-generation approaches"
     *    - The requirement states "Make password-generation behavior swappable"
     *    - Strategy pattern encapsulates each algorithm (basic, enhanced, letters) as separate
     *      classes implementing the PasswordAlgorithm interface
     *    - The setAlgorithm() method allows runtime selection of strategies
     *    - New algorithms can be added by implementing PasswordAlgorithm without modifying
     *      client code or the PasswordGeneratorService class
     *    - This satisfies the requirement for future expansion without modification to client code
     *    - The generatePassword() method delegates to the selected strategy, making behavior
     *      swappable at runtime
     * 
     * ============================================================================
     */
    
    private static PasswordGeneratorService instance;
    private PasswordAlgorithm currentAlgorithm;
    private static final Map<String, PasswordAlgorithm> ALGORITHMS = new HashMap<>();
    
    static {
        ALGORITHMS.put("basic", new BasicAlgorithm());
        ALGORITHMS.put("enhanced", new EnhancedAlgorithm());
        ALGORITHMS.put("letters", new LettersAlgorithm());
    }
    
    /**
     * Private constructor to prevent external instantiation.
     * This enforces the Singleton pattern.
     */
    private PasswordGeneratorService() {
        // Private constructor for Singleton pattern
    }
    
    /**
     * Returns the single instance of PasswordGeneratorService.
     * If no instance exists, creates one. This method implements the Singleton pattern.
     * 
     * @return the single instance of PasswordGeneratorService
     */
    public static PasswordGeneratorService getInstance() {
        if (instance == null) {
            instance = new PasswordGeneratorService();
        }
        return instance;
    }
    
    /**
     * Sets the password generation algorithm to use.
     * Supported algorithms: "basic", "enhanced", "letters".
     * This method implements the Strategy pattern by allowing runtime selection
     * of different password generation strategies.
     * 
     * @param name the name of the algorithm to use
     * @throws IllegalArgumentException if the algorithm name is not supported
     */
    public void setAlgorithm(String name) {
        PasswordAlgorithm algorithm = ALGORITHMS.get(name);
        if (algorithm == null) {
            throw new IllegalArgumentException("Unsupported algorithm: " + name);
        }
        this.currentAlgorithm = algorithm;
    }
    
    /**
     * Generates a password of the specified length using the currently selected algorithm.
     * 
     * @param length the desired length of the password
     * @return a password string generated by the selected algorithm
     * @throws IllegalStateException if no algorithm has been set before calling this method
     */
    public String generatePassword(int length) {
        if (currentAlgorithm == null) {
            throw new IllegalStateException("No algorithm has been set. Call setAlgorithm() first.");
        }
        return currentAlgorithm.generate(length);
    }
    
    /**
     * Resets the current algorithm to null. This is package-private and intended
     * for testing purposes to ensure test isolation when using the singleton pattern.
     */
    void resetAlgorithm() {
        this.currentAlgorithm = null;
    }
}

